### ISSUE TITLE
TFS build task: publishing features with multiple branches

### ISSUE THREAD

**Issue by timvandelockand** [Augurk/Augurk#18]
When using the TFS build task through PublishFeaturesToAugurk.ps1 it's not supported to have different feature files on multiple branches. If a feature file doesn't exist in a particular branch the build for that branch will fail (or partially succeed when configured that way).

This could be solved by providing an option to use the parent folder names of the feature files as the group name in Augurk (that way only existing feature files will be processed).

**Comment by marktaling** [comment]
I'm not sure I correctly understand the issue. The buildtask does not require you to specify specific feature files but rather requires you to provide a path from where it recursively should search for .feature files.
Following this logic, there should be no issue when a file only exists on a single branch.

**Comment by timvdl92** [comment]
Indeed, when the file matches an existing pattern there's no problem. When a new branch needs a .feature file in a new group in Augurk though, a build step with a new pattern would have to be added. In that case the path will not be found in other branches that already existed.

**Comment by marktaling** [comment]
So, the problem is mostly that in your case the build step references a folder which is not necessarily present on al branches?

**Comment by timvdl92** [comment]
Exactly. Now I could enable 'Continue on error' on those specific build steps, but the build will then only partially succeed (which could indicate that there's something wrong, while it is expected behaviour in that case)

**Comment by marktaling** [comment]
I think this particular build step is fine as-is. As you do not always have an hierarchical folder structure you want to mimic in Augurk. 
I suggest we add a second task which has the described functionality. This new task would not allow you to specify a GroupName but instead use the parentfolders of each file as a GroupName. This would allow you to do grouping on a branch-level while still supporting the use of a single builddefinition.

**Comment by jmezach** [comment]
I don't think having a second task with similar functionality is a good idea. First of all, it makes it confusing for our users because they need to decide which Augurk task to use. Second of all its not very easy to share functionality between these two tasks, so for us it becomes a maintenance nightmare.

Perhaps we should just add a checkbox indicating which behaviour to use and then make the GroupName field disappear based on that.

**Comment by marktaling** [comment]
That would work fine as well. The main thing is, I don't want to lose our current functionality.

**Comment by jmezach** [comment]
Interestingly if I look at how things are set up now (ie. our problem domain ;)) we not only have to look at the direct parent, but also parent folders above that. So I have two questions:

- How far do we go with this? Keep going until we hit the folder we started searching from? At the moment that would be the folder the build is run in, which might not always be what you want. Perhaps add a base folder option for the search as well?
- What do we with each sub level in terms of naming the group? Ie. what does the group name become if the sub folder structure is something like \Specifications\Client\Business policy\PauseProfile?

**Comment by marktaling** [comment]
I would assume we only support the highest level. So we would always take the direct parent folder?
It's easiest to implement and clear in the way it functions.

**Comment by jmezach** [comment]
@timvandelockand Is this still an issue?

**Comment by timvandelockand** [comment]
Not anymore; the 'use folder structure' checkbox works like a charm.

**Comment by jmezach** [comment]
This has been fixed already. We have also recently moved the VSTS/TFS extension to its own repo (https://github.com/augurk/vsts-extension)
