### ISSUE TITLE
Pressing "Enter" or "Return" after a search refreshes the page

### ISSUE THREAD

**Issue by marktaling** [Augurk/Augurk#223]
As indicated in the title, when pressing "Enter" or "Return" after typing a search, the page will refresh effectively cancelling your search.

**Comment by tristanhollman** [comment]
Perhaps it might also be a good idea to make the 'searching' process more visible to the user.
For example by adding some sort of loading icon while searching for results.
This would make it much clearer for the user that Augurk already started searching.

**Comment by marktaling** [comment]
This has been shipped as part of the 3.1.0-preview and will be part of the final product.
