### ISSUE TITLE
Check IIS modules upon installing

### ISSUE THREAD

**Issue by roycornelissen** [Augurk/Augurk#25]
After installing the Augurk WebDeploy package, I got 405 Method Not Allowed errors from IIS on some DELETE calls. They were caused by the _WebDavModule_ being present in the IIS application. The installer should check and delete the module if present. Request filtering may also hinder the API, when the _DELETE_ verb is blocked. On application level, _DELETE_ should be allowed, maybe best if it's done explicitly.

**Comment by marktaling** [comment]
This should be resolved by implementing #36, which eliminates the need to use IIS at all.

**Comment by marktaling** [comment]
This will be resolved as part of #58.
