### ISSUE TITLE
Getting HTTP 404 on two fonts in the Augurk site

### ISSUE THREAD

**Issue by roycornelissen** [Augurk/Augurk#27]
If you open the website and look at the requests in Fiddler, I had 2 404 errors:

/Augurk/fonts/glyphicons-halflings-regular.woff
/Augurk/fonts/glyphicons-halflings-regular.woff2

These are part of the solution but probably not deployed with the WebDeploy?

**Comment by jmezach** [comment]
Looks like this is a mime-mapping problem with IIS. We've seen this problem before with other projects. Will probably only require a configuration change. Should be easy to fix.

**Comment by jmezach** [comment]
It was indeed a mime-mapping issue with IIS. We've added the proper mapping to the Web.config file in Augurk so that this should no longer be an issue in future versions.
