### ISSUE TITLE
Editing feature files directly in Augurk

### ISSUE THREAD

**Issue by marktaling** [Augurk/Augurk#32]
At the Dutch SpecFlow Users meetup a couple of people suggested that it would be a great help if feature files could be edited in Augurk directly. Curiously enough those users actually store their feature files in a version control environment (e.g. Git, TFVC, etc...).

For this specific scenario it might be a neat solution to create a "suggest change" feature. This would allow a user to suggest a change to the feature file in Augurk. A more technical user will at a later time retrieve those changes through a Visual Studio plugin and process them.

Would this be a usable feature? Discuss!

**Comment by marktaling** [comment]
Perhaps this could be combined with #2 review functionality?

**Comment by roycornelissen** [comment]
Yes I think #2 would be the best start for this, as the main objective would be to get input from the business users that won't be using Visual Studio. If they are able to input feedback on specific features or maybe specific lines in scenarios, then the analyst can process that feedback and edit the scenarios in Visual Studio. This way you can maintain the comments/suggestions in your own Augurk database. The upside is also that you won't be causing conflicting changes to the features themselves, or have a business user with no specific Cucumber knowledge to break the feature files.

But being able to get input via Augurk would be a huge benefit. As suggested, a Medium.com type of user experience would be great.

**Comment by BertrandR** [comment]
I ment something different then what is described in #2

For me the most basic feature would be to simply edit the feature files as they are stored in source control. I understand objections about 'business people' breaking feature files (and automated testing), but in my experience even people with very limited IT experience are able to edit that is, build upon, feature files. For example in one of my projects an actuary worked a great deal on the feature files by expanding existing specifcations. 

Building upon basic editing functionality I can envision things like:
-Only allow editing of existing structures like tables
-Check if the feature file is still 'valid' Cucumber (parsing)
-Prefix new specifications with a set tag (so it can be excluded in the build, maybe the @notyetimplemented tag)

**Comment by jmezach** [comment]
We don't believe Augurk should be used as an editing tool. First of all it would increase the complexity of Augurk itself a fair bit, but also we feel that whenever you edit the feature file you'll probably need to make changes to the code as well. Closing this for now. If people still feel this is important, do not hesitate to re-open this issue.
