### ISSUE TITLE
Self-hosted Augurk

### ISSUE THREAD

**Issue by marktaling** [Augurk/Augurk#36]
Currently Augurk has to be hosted in IIS. As it has been build upon the OWIN stack, it would be preferable to self-host it in it's own process. This would simplify the deployment and upgrade scenarios...

**Comment by jmezach** [comment]
Perhaps we could look into ASP.NET Core? This would make self-hosting quite easy since an ASP.NET Core app is just another executable which you can just xcopy deploy and run. Biggest problem for this right now though is Raven as it doesn't support .NET Core as far as I can tell.

**Comment by marktaling** [comment]
This issue will be closed. One of the roadmap points is making Augurk cross-platform, which will mean other hosting anyway.
