### ISSUE TITLE
Feature Request: Overview of failed scenario's

### ISSUE THREAD

**Issue by jmezach** [Augurk/Augurk#4]
An overview page of scenario's that failed would be nice ;).

**Comment by marktaling** [comment]
Is this feature still required? At this moment I am wondering if the integration with testresults is actually implemented correctly. Right now we just parse MS-Test results. Wouldn't it be better to search for a form of integration with tools like MTM?

**Comment by marktaling** [comment]
At this moment Augurk does not support processing testresults at all. This issue will be revisited once we will re-implement the support for testresults.
