### ISSUE TITLE
Product landing pages

### ISSUE THREAD

**Issue by jmezach** [Augurk/Augurk#44]
Since we've talked about this and we've also got it listed on the public website I thought we'd might as well make it official and post a feature request here ;).

The idea here is to have an editable landing page for a product so serve as an entry-point into the rest of the documentation for the product contributed by the feature files.

**Comment by marktaling** [comment]
Ideally, each product would start out with a default/empty page. The page should also allow the user to add new markdown which then replaces the empty page.

Aditionally, there should be a page where product pages can be maintained. Ideally this page would also be used to add or remove products.
