### ISSUE TITLE
Upgrade to RavenDb 4.0

### ISSUE THREAD

**Issue by jmezach** [Augurk/Augurk#54]
There is a pre-release candidate of RavenDb 4.0 out now. We might want to look into upgrading to that version, since it should also be able to run on .NET Core, which would make Augurk a lot more portable to other platforms.

It looks like it it's not a drop-in replacement though, so we should investigate what it takes to upgrade to this new version.

**Comment by marktaling** [comment]
Currently RavenDB is still in RC. It would have been released in December but there appear to be some delays.
We can however, start contacting RavenDB to check whether they are willing to provide us a new opensource license or whether we should switch to a community license.
