### ISSUE TITLE
Markdown: Text to UML Sequence diagram

### ISSUE THREAD

**Issue by anthonyhuebers** [Augurk/Augurk#64]
Hello,

We are looking into Augurk as a possible replacement voor Pickles. For that we would like to have a markdown feature that converts a part of the feature file description to an UML Sequence diagram. https://bramp.github.io/js-sequence-diagrams/ is an example of text to UML Sequence diagram functionality that we are looking for.

Greetings, 
Anthony

**Comment by GijsvanDulmen** [comment]
Sounds like a great feature. PlantUML support would be even better?

**Comment by anthonyhuebers** [comment]
Currently our documentation exist of a set of Adoc (some kind of Markdown) files combined with Pickles. This results in a documentation container for every build.

In Adoc we use the PlantUML syntax to define for example Component Diagrams and Sequence Diagrams. These Sequence Diagrams are mostly used to describe the flow of a feature(file). At the moment next to a .feature file we add a .adoc file for the features that have one or more sequence diagrams. 

With asciidoctor we generate the documentation for all the .adoc files combined and with the asciidoctor diagram plugin we get our diagrams within the documentation but, this documentation is not integrated with Pickles.

What we would like to have these feature Sequence Diagrams added to the Specflow documentation of that specific feature. We also want to have one integrated opensource tool that is able to furfill these needs.

Preferably we would like to stick to the plantuml syntax but are in a fase that we are still able to switch to a different syntax if needed. As a alternative to the PlantUML system we thought of integrating a javascript framework/plugin that generates the drawings on the fly within the .html files provided by for example Pickles. But we prefer to use a tool that includes these text to digram features instead of reinventing the weel our self.

**Comment by marktaling** [comment]
Later today we hope to release the first part of our effort to support UML, sadly this does net yet includes Sequence Diagrams. Those should follow in the next few weeks.
![image](https://user-images.githubusercontent.com/6681159/46727764-8dffd000-cc81-11e8-950f-a63262c6f8fa.png)

Similar to the "generic"  UML above we will implement code blocks for sequence diagrams, eg;:
```
    ```Sequence
    Your sequence diagram
    ```
```

**Comment by anthonyhuebers** [comment]
That looks great! Please notify us when Sequence Diagrams are added!

**Comment by jmezach** [comment]
With the release of [2.8.0](https://github.com/augurk/augurk/releases/2.8.0) we have also enabled support for sequence diagrams:

<img width="856" alt="screenshot 2018-11-21 10 18 19" src="https://user-images.githubusercontent.com/1225489/48831340-eba23480-ed76-11e8-8ae7-d08317873544.png">
