### ISSUE TITLE
Automatically include a list of scenario's in the published feature file

### ISSUE THREAD

**Issue by harrynieboer** [Augurk/Augurk#8]
Currently we manually add an index of the scenario's per feature file to the file itself to get a quick overview of the content of the feature.
It would be nice when this index would be generated automatically because the manual index gets easyly out of sync.
Placement would be before the first scenario and before the background.

**Comment by jmezach** [comment]
We don't feel like there is a high demand for this feature. If more people are interested in this, feel free to re-open this issue.
