### ISSUE TITLE
View examples in specification

### ISSUE THREAD

**Issue by maartengo** [Augurk/Augurk#90]
Currently examples are only shown as a table and the specification still shows the placeholders for te examples, as shown below.

![afbeelding](https://user-images.githubusercontent.com/46345801/56581523-b23f5080-65c4-11e9-9e85-7cd36de7dd98.png)

To be able to read the specification better I'd like to be able to select a example row and have it's values entered in the specification; (in this case VBS is selected) 
![afbeelding](https://user-images.githubusercontent.com/46345801/56581757-32fe4c80-65c5-11e9-8ad5-0792d0ce4e87.png)

**Comment by jmezach** [comment]
Ah, yes, this is something @marktaling and I have often discussed as a nice to have feature. I believe we even have a scenario written for it, but we never really had the time to implement it nor had much need for it ourselves.

We're currently busy with our cross platform story, so it's not going to be high up on our priority list right now. If you're able and willing to help out with this feel free to submit a pull request. We're more than happy to discuss the design of such a feature, but I don't see us finding the time to implement this soon. @marktaling correct me if I'm wrong here ;)

**Comment by marktaling** [comment]
We will include this in the 3.0 release.
