### ISSUE TITLE
Identical feature names in different groups is not shown in the menu

### ISSUE THREAD

**Issue by RemcoSpil** [Augurk/Augurk#95]
When a feature name is used in multiple groups, it will only be included in the menu for one group.
Although it is possible to request the feature via the url

Reposteps:
- Add a feature called 'Test feature' to group 'Groupname 1'
- Add a feature called 'Test feature' to group 'Groupname 2'

Open the augurk website:
- 'Test feature' only shows under 'Groupname 1' in the menu

**Comment by jmezach** [comment]
This was a bug that is fixed for 3.0. We hope to ship 3.0 sometime this week.
